//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness_Life.CMD.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fitness_Life.CMD.Languages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить прием пищи нажмите &quot;Е&quot;.
        /// </summary>
        internal static string AddFood {
            get {
                return ResourceManager.GetString("AddFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите количество каллорий.
        /// </summary>
        internal static string CaloriesProduct {
            get {
                return ResourceManager.GetString("CaloriesProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите колличество углеводов.
        /// </summary>
        internal static string Capbohydrates {
            get {
                return ResourceManager.GetString("Capbohydrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите дату рождения.
        /// </summary>
        internal static string EnterBirthdate {
            get {
                return ResourceManager.GetString("EnterBirthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пол.
        /// </summary>
        internal static string EnterGender {
            get {
                return ResourceManager.GetString("EnterGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите рост.
        /// </summary>
        internal static string EnterHeight {
            get {
                return ResourceManager.GetString("EnterHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя пользователя.
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя продукта .
        /// </summary>
        internal static string EnterProductName {
            get {
                return ResourceManager.GetString("EnterProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите вес.
        /// </summary>
        internal static string EnterWeight {
            get {
                return ResourceManager.GetString("EnterWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите количество жиров в продукте.
        /// </summary>
        internal static string FatsProduct {
            get {
                return ResourceManager.GetString("FatsProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вас приветствует приложение Fitness Life!.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите количество белков в продукте.
        /// </summary>
        internal static string ProteinsProduct {
            get {
                return ResourceManager.GetString("ProteinsProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите вес порции.
        /// </summary>
        internal static string WeightProducts {
            get {
                return ResourceManager.GetString("WeightProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что вы хотите делать.
        /// </summary>
        internal static string WhatToDo {
            get {
                return ResourceManager.GetString("WhatToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат записи.
        /// </summary>
        internal static string WrongFormat {
            get {
                return ResourceManager.GetString("WrongFormat", resourceCulture);
            }
        }
    }
}
